name: "Genshin Impact Helper"

on:
  workflow_dispatch:  # 手动触发
  schedule:  # 计划任务触发
    - cron: '10 16 * * *'  # scheduled at 00:10 (UTC+8) everyday
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  watch:
    types: [started]

env:
  TZ: 'Asia/Shanghai'

jobs:
  run-it-genshin-mys-checkin:
    name: Genshin MYS Checkin on action
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04
    env:
      working-directory: ${{ github.workspace }}

    steps:
      # 设置服务器时区为东八区 
      # - name: Set time zone
      #   run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          repository: y1ndan/genshinhelper
          # path: 'genshinhelper'
          token: ${{ secrets.ACCESS_TOKEN || github.token }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # working-directory: ./genshinhelper

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: |
          sleep $(shuf -i 10-30 -n 1)
          # sleep $(($RANDOM % 600))

      - name: Setting and Run checkin
        env:
          COOKIE_MIHOYOBBS: ${{ secrets.COOKIE_MIHOYOBBS }}
          COOKIE_MIYOUBI: ${{ secrets.COOKIE_MIYOUBI }}
          COOKIE_WEIBO: ${{ secrets.COOKIE_WEIBO }}
          COOKIE_KA: ${{ secrets.COOKIE_KA }}
        run: |
          echo "${{ secrets.COOKIE_MIHOYOBBS }}" | tr '#' "\n" | xargs -I {} sh -c 'echo "{}" | python3 genshinhelper'
        # working-directory: ./genshinhelper

  run-it-genshin-mys-checkin-w:
    name: Genshin MYS Checkin W on action
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04
    env:
      RUN_CACHE: ${{ !!secrets.WB_CONFIG }}
      working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          repository: Tsuk1ko/genshin-mys-checkin
          # path: 'genshin-mys-checkin'
          token: ${{ secrets.ACCESS_TOKEN || github.token }}

      - name: Cache
        if: env.RUN_CACHE == 'true'
        uses: actions/cache@v2
        with:
          path: cache
          key: gc-cache-v3-${{ github.run_id }}
          restore-keys: |
            gc-cache-v3-

      - name: Set up Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install
        # working-directory: ./genshin-mys-checkin

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: |
          sleep $(shuf -i 10-30 -n 1)
          # sleep $(($RANDOM % 600))

      - name: Setting and Run checkin
        continue-on-error: true
        env:
          COOKIE: ${{ secrets.COOKIE_MIHOYOBBS }}
          WB_CONFIG: ${{ secrets.WB_CONFIG }}
        run: yarn start
        # working-directory: ./genshin-mys-checkin
